# Generated by Django 3.1.4 on 2021-02-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_category_db'),
    ]

    operations = [
        migrations.AddField(
            model_name='products_db',
            name='categ',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
