# Generated by Django 3.1.4 on 2021-01-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True)),
                ('mobileno', models.CharField(max_length=25, null=True)),
                ('email', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
