# Generated by Django 3.1.4 on 2021-02-03 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_category_db'),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=10, null=True)),
                ('Cmail', models.EmailField(blank=True, max_length=15, null=True)),
                ('Total', models.IntegerField(blank=True, null=True)),
                ('productid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.products_db')),
            ],
        ),
    ]
