# Generated by Django 3.1.4 on 2021-02-03 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Total',
        ),
    ]
