# Generated by Django 3.1.4 on 2021-02-07 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_remove_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
