# Generated by Django 3.1.4 on 2021-02-09 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cart_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
