# Generated by Django 3.1.4 on 2021-02-15 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210214_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='Total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
