# Generated by Django 3.1.4 on 2021-02-22 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210215_1317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Cmail',
        ),
    ]
