# Generated by Django 3.1.4 on 2021-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
