# Generated by Django 3.2.16 on 2023-01-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_cart_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='Username',
        ),
    ]
